boot.o: boot.S multiboot.h x86_desc.h types.h
interrupt_service_routines.o: interrupt_service_routines.S \
  interrupt_service_routines.h
system_call_linkage.o: system_call_linkage.S system_call_linkage.h
x86_desc.o: x86_desc.S x86_desc.h types.h
exception_handlers.o: exception_handlers.c x86_desc.h types.h lib.h \
  i8259.h exception_handlers.h processes.h system_calls.h rtc.h \
  file_system.h keyboard.h system_call_linkage.h
file_system.o: file_system.c file_system.h types.h system_calls.h lib.h \
  rtc.h keyboard.h processes.h system_call_linkage.h x86_desc.h
i8259.o: i8259.c i8259.h types.h lib.h
init_idt.o: init_idt.c x86_desc.h types.h lib.h i8259.h init_idt.h \
  exception_handlers.h interrupt_service_routines.h keyboard.h rtc.h \
  system_calls.h file_system.h processes.h system_call_linkage.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h keyboard.h paging.h rtc.h file_system.h system_calls.h \
  processes.h system_call_linkage.h
keyboard.o: keyboard.c lib.h types.h i8259.h keyboard.h
lib.o: lib.c lib.h types.h
paging.o: paging.c paging.h lib.h types.h
processes.o: processes.c processes.h types.h system_calls.h lib.h rtc.h \
  file_system.h keyboard.h system_call_linkage.h paging.h x86_desc.h
rtc.o: rtc.c rtc.h types.h lib.h i8259.h
system_calls.o: system_calls.c system_calls.h lib.h types.h rtc.h \
  file_system.h keyboard.h processes.h system_call_linkage.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h init_idt.h \
  exception_handlers.h file_system.h system_calls.h rtc.h keyboard.h \
  processes.h system_call_linkage.h
